Fix minor errors in docs
adafruit/Adafruit_CircuitPython_MatrixPortal pull request #91
Opened 2023-07-09 20:08 UTC by rhooper

Fixes docs:
- Serpentine => serpentine
- tiles_rows =>  tile_rows

2023-07-09 21:38 UTC, dhalbert requested changes

2023-07-09 21:38 UTC, dhalbert commented on adafruit_matrixportal/matrixportal.py
> +    :param bool derpentine: Used when panels are arranged in a serpentine pattern rather
:smiley: 
```suggestion
    :param bool serpentine: Used when panels are arranged in a serpentine pattern rather
```

2023-07-10 16:24 UTC, dhalbert commented
Something is busted about the build -- not sure what the problem is, since your change was so innocuous.

2023-07-10 16:31 UTC, dhalbert commented
@makermelissa Do you understand why the build is failing?

2023-07-10 21:48 UTC, FoamyGuy commented
@dhalbert and @makermelissa 

It appears there has been a recent new major release for [pillow](https://github.com/python-pillow/Pillow/releases)

And amongst the release notes it lists this:

> Remove deprecated ImageFont.getsize and related functions for Pillow 10.0.0 https://github.com/python-pillow/Pillow/pull/7080 [@radarhere]

In Blinka_Displayio it's attempting to use the `getsize()` function here: https://github.com/adafruit/Adafruit_Blinka_Displayio/blob/61102c93bfb90fbccc4bc21122444531ebe2dd84/fontio.py#L78

I'm not entirely sure why it manifested itself in this particular way on this PR, but I think the options to resolve it for now are:

- pin `pillow` to a lower release version number
- Change fontio.py in Blinka_Displayio to use a different non-deprecated API, hopefully the functionality has just moved elsewhere and not been removed entirely.

2023-07-10 22:14 UTC, radarhere commented
Hi.

> Change fontio.py in Blinka_Displayio to use a different non-deprecated API, hopefully the functionality has just moved elsewhere and not been removed entirely.

You can read at https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#font-size-and-offset-methods that `ImageFont.getsize()` has been replaced by `ImageFont.getbbox()`

2023-07-10 22:19 UTC, FoamyGuy commented
Thank you. Sorry to ping you, I didn't think to pull the "@" out of the line I copied from the release notes.

2023-07-11 00:22 UTC, makermelissa commented
> I'm not entirely sure why it manifested itself in this particular way on this PR, but I think the options to resolve it for now are:
> 
> * pin `pillow` to a lower release version number
> * Change fontio.py in Blinka_Displayio to use a different non-deprecated API, hopefully the functionality has just moved elsewhere and not been removed entirely.

I'm fairly sure it installs Blinka Displayio unless you add **displayio** to `autodoc_mock_imports` in https://github.com/adafruit/Adafruit_CircuitPython_MatrixPortal/blob/main/docs/conf.py, so that's another possible fix. However, I think fixing it it in Blinka_Displayio would be the preferred fix.

2023-07-12 15:30 UTC, makermelissa commented
@dhalbert the build is now passing if you want to approve unless you had some other requested changes.

2023-08-23 22:32 UTC, FoamyGuy approved these changes
This looks good to me.

we can always use a new PR if there are any further changes that come up.

2023-08-23 22:33 UTC, merged